# Generated by Django 4.0 on 2021-03-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0003_roster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='team_name',
            new_name='roster_name',
        ),
    ]
