# Generated by Django 4.0 on 2021-03-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0004_rename_team_name_roster_roster_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tagger.roster'),
        ),
    ]
