# Generated by Django 4.0 on 2021-03-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0005_player_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='time started')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_type', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(verbose_name='time made')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tagger.game')),
            ],
        ),
    ]
