# Generated by Django 4.0 on 2021-04-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0013_auto_20210420_1611'),
        ('tagger', '0013_auto_20210420_1620'),
    ]

    operations = [
    ]
