# Generated by Django 4.0 on 2021-04-21 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0015_auto_20210421_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='atBat',
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 45, 48, 649656, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 45, 48, 649630, tzinfo=utc), verbose_name='time started'),
        ),
    ]
