# Generated by Django 4.0 on 2021-04-21 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0016_auto_20210421_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitch_set', to='tagger.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 48, 45, 286766, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 48, 45, 286740, tzinfo=utc), verbose_name='time started'),
        ),
    ]
