# Generated by Django 4.0 on 2021-04-21 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0017_auto_20210421_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='batter',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='pitcher',
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 50, 33, 650509, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 50, 33, 650484, tzinfo=utc), verbose_name='time started'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tagger.game'),
        ),
    ]
