# Generated by Django 4.0 on 2021-04-22 01:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0020_auto_20210422_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 1, 0, 15, 888264, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 1, 0, 15, 888236, tzinfo=utc), verbose_name='time started'),
        ),
    ]
